/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ChoiceOfModul.java
 *
 * Created on 22/07/2010, 13:48:27
 */

package invuler;

/**
 *
 * @author Ro
 */
public class ChoiceOfModule extends javax.swing.JDialog {

   
    /**
     * 
     * @param janela
     * @param modal
     */
    public ChoiceOfModule(JanelaPrincipal janela, boolean modal) {
        super(janela, modal);
        initComponents();
    }
    String module="";
    int pos= -1;

    /**
     * 
     * @return The module name.
     */
    public String getModule() {
        return module;
    }

    /**
     * Set the module name that will be used to analyze the code.
     * @param module
     */
    public void setModule(String module) {
        this.module = module;
    }

    /**
     * 
     * @return The position of the module name at the drop down menu.
     */
    public int getPos() {
        return pos;
    }

    /**
     * 
     * @param pos
     */
    public void setPos(int pos) {
        this.pos = pos;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt_ChoiceModule = new javax.swing.JButton();
        cb_ChoiceModule = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        bt_ChoiceModule.setText("OK");
        bt_ChoiceModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ChoiceModuleActionPerformed(evt);
            }
        });

        cb_ChoiceModule.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Java", "PHP", "ASP.NET", "JavaScript" }));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Identifique a linguagem de programação para análise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cb_ChoiceModule, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_ChoiceModule, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_ChoiceModule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_ChoiceModule))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_ChoiceModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ChoiceModuleActionPerformed
            module = (String) cb_ChoiceModule.getSelectedItem();
            pos = cb_ChoiceModule.getSelectedIndex();
            dispose();
    }//GEN-LAST:event_bt_ChoiceModuleActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChoiceOfModule dialog = new ChoiceOfModule(new JanelaPrincipal(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_ChoiceModule;
    private javax.swing.JComboBox cb_ChoiceModule;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
